### ISSUE TITLE
How to upgrade Node.js in Homestead

### ISSUE THREAD

**Issue by mirbatworks** [laravel/homestead#491]
My Vagrant Box is up to date, but Node is 5.7 version and in Laravel 5.4 I have a problem with laravel-mix. I would like to upgrade Node.js to try to solve problem with laravel-mix. This is error that I get when I run `npm run dev`

```
vagrant@homestead:~/www/blog$ npm run dev

> @ dev /home/vagrant/www/blog
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/vagrant/www/blog/node_modules/laravel-mix/setup/webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/www/blog/npm-debug.log
```
Log:
[npm-debug.log.zip](https://github.com/laravel/homestead/files/802205/npm-debug.log.zip)

**Comment by svpernova09** [comment]
Do you get the same errors when you run `npm run dev` from your host OS?

**Comment by mirbatworks** [comment]
After vagrant ssh I navigate to my project folder and run npm run dev. It's fresh copy of Laravel 5.4. I'm not sure that I understand you from where I need to run command when you said host OS. In my old Laravel 5.3 project everything works fine with gulp command.

**Comment by svpernova09** [comment]
Your Host OS is the OS that you're running on your computer. Windows, MacOS, Linux?

The same window you ran `vagrant ssh` in, run `exit` and then `npm run dev` and see if you get the same errors. Also try the old tried and true Node debugging method of `rm -rf node_modules && npm install && npm run dev`

**Comment by mirbatworks** [comment]
```
mirbatworks@mirbatworks-desktop:~/Homestead$ npm run dev
The program 'npm' is currently not installed. You can install it by typing:
sudo apt install npm
mirbatworks@mirbatworks-desktop:~/Homestead$ 
```
Jeffrey said that I need to update my installed  version of Node. How to do that in Homestead?

**Comment by svpernova09** [comment]
Just like you would in any other version of Linux. http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts
