### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by driesvints** [laravel/homestead#53]
I was getting an error for unsupported locale setting when I tried to run a command that wasn't installed. This is the full error log:

``` sh-session
vagrant@homestead:~/code/driesvints/driesvints.com$ sass
Sorry, command-not-found has crashed! Please file a bug report at:
https://bugs.launchpad.net/command-not-found/+filebug
Please include the following information with the report:

command-not-found version: 0.3
Python version: 3.4.0 candidate 1
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
Exception information:

unsupported locale setting
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/CommandNotFound/util.py", line 24, in crash_guard
    callback()
  File "/usr/lib/command-not-found", line 69, in main
    enable_i18n()
  File "/usr/lib/command-not-found", line 40, in enable_i18n
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.4/locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

I fixed it with the following solution: http://askubuntu.com/questions/205378/unsupported-locale-setting-fault-by-command-not-found

Now I get a correct error message:

``` sh-session
vagrant@homestead:~/code/driesvints/driesvints.com$ sass
The program 'sass' is currently not installed. To run 'sass' please ask your administrator to install the package 'ruby-sass'
```

Has anyone else experienced this problem?

**Comment by svpernova09** [comment]
Closing this issue as old and we've just reenabled issues on the Homestead Repo. 

If you're still having issues please open a new issue and link to this issue. Thanks!
