### ISSUE TITLE
ETXTBSY

### ISSUE THREAD

**Issue by KuGelFaaaNg** [laravel/homestead#922]
Since I have reinstalled my operating system, I can no longer install a NPM package in my box. 

Now I turn to you because I have tried almost everything.
The error is already known. There are many solutions, but none helped me to install at least one package. 

## Some steps I tried

* run npm on clean install, everything up to date
* run npm i -g npm@5.6.0 which downgrades the npm to version 5.6.0 
* fresh installation of homestead and laravel
* try with different boxes (one in project and a box outside of the project)
* npm install --no-bin-links
*  npm i -g npm
* ``` config.vm.provider "virtualbox" do |v| v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"] end```
* npm install -f
* [Github-NPM-20950](https://github.com/npm/npm/issues/20950)

## Versions
  - Vagrant: 6.3.0
  - Provider: Virtualbox
  - Homestead: branch master

## Host operating system
Windows 10

## Homestead.yaml
```yaml
ip: "192.168.10.11"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    -
        map: C:\project
        to: /home/vagrant/code
sites:
    -
        map: domain.test
        to: /home/vagrant/code/public
     
databases:
    - homestead
```

## Expected behavior
NPM should be able to install packages.

### npm install

```shell

npm WARN rollback Rolling back acorn-dynamic-import@2.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/acorn-dynamic-import/package.json.1881664473'
npm WARN rollback Rolling back abbrev@1.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/abbrev/package.json.131979142'
npm WARN rollback Rolling back camelcase@1.2.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/adjust-sourcemap-loader/node_modules/camelcase/package.json.3608494142'
npm WARN rollback Rolling back ajv-keywords@3.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ajv-keywords/package.json.79073451'
npm WARN rollback Rolling back acorn@4.0.13 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/acorn-dynamic-import/node_modules/acorn/package.json.3744946582'
npm WARN rollback Rolling back ansi-regex@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-regex/package.json.1836769090'
npm WARN rollback Rolling back ansi-html@0.0.7 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-html/package.json.3526147613'
npm WARN rollback Rolling back amdefine@1.0.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/amdefine/package.json.2193192644'
npm WARN rollback Rolling back alphanum-sort@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/alphanum-sort/package.json.2414905121'
npm WARN rollback Rolling back ansi-wrap@0.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-wrap/package.json.3490830398'
npm WARN rollback Rolling back ansi-gray@0.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-gray/package.json.447563765'
npm WARN rollback Rolling back aproba@1.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aproba/package.json.1329902612'
npm WARN rollback Rolling back archive-type@3.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/archive-type/package.json.2826290367'
npm WARN rollback Rolling back arr-flatten@1.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-flatten/package.json.4149963837'
npm WARN rollback Rolling back array-flatten@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-flatten/package.json.3323225995'
npm WARN rollback Rolling back arr-diff@4.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-diff/package.json.2697774172'
npm WARN rollback Rolling back array-find-index@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-find-index/package.json.1868268675'
npm WARN rollback Rolling back arr-union@3.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-union/package.json.3688768057'
npm WARN rollback Rolling back file-type@3.9.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/archive-type/node_modules/file-type/package.json.1330747326'
npm WARN rollback Rolling back array-uniq@1.0.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-uniq/package.json.560861751'
npm WARN rollback Rolling back array-differ@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-differ/package.json.7146712'
npm WARN rollback Rolling back array-unique@0.3.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-unique/package.json.2128389478'
npm WARN rollback Rolling back asap@2.0.6 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/asap/package.json.80490974'
npm WARN rollback Rolling back array-union@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-union/package.json.3889469262'
npm WARN rollback Rolling back assert-plus@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/assert-plus/package.json.2748921949'
npm WARN rollback Rolling back assign-symbols@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/assign-symbols/package.json.2963401165'
npm WARN rollback Rolling back async-foreach@0.1.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-foreach/package.json.101267636'
npm WARN rollback Rolling back async-each-series@1.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-each-series/package.json.4235654441'
npm WARN rollback Rolling back async-each@1.0.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-each/package.json.1575426565'
npm WARN rollback Rolling back asynckit@0.4.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/asynckit/package.json.1658358553'
npm WARN rollback Rolling back babel-plugin-syntax-exponentiation-operator@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-exponentiation-operator/package.json.2605814095'
npm WARN rollback Rolling back atob@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/atob/package.json.1109470979'
npm WARN rollback Rolling back ansi-styles@2.2.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-code-frame/node_modules/ansi-styles/package.json.2120478720'
npm WARN rollback Rolling back babel-plugin-syntax-async-functions@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-async-functions/package.json.168691491'
npm WARN rollback Rolling back aws4@1.8.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aws4/package.json.1861900808'
npm WARN rollback Rolling back aws-sign2@0.7.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aws-sign2/package.json.1057946594'
npm WARN rollback Rolling back babel-plugin-syntax-object-rest-spread@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-object-rest-spread/package.json.3434926040'
npm WARN rollback Rolling back babel-plugin-syntax-flow@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-flow/package.json.697706027'
npm WARN rollback Rolling back babel-plugin-syntax-trailing-function-commas@6.22.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-trailing-function-commas/package.json.1884523917'
npm WARN rollback Rolling back babylon@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babylon/package.json.1534529194'
npm WARN rollback Rolling back babel-plugin-syntax-jsx@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-jsx/package.json.1061184787'
npm WARN rollback Rolling back balanced-match@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/balanced-match/package.json.802883423'
npm WARN rollback Rolling back batch@0.6.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/batch/package.json.891624474'
npm WARN rollback Rolling back base64-js@0.0.8 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/base64-js/package.json.3356521399'
npm WARN rollback Rolling back beeper@1.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/beeper/package.json.3292473503'
npm WARN rollback Rolling back babel-code-frame@6.26.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-code-frame/node_modules/ansi-styles/package.json.2120478720'
npm WARN rollback Rolling back babel-core@6.26.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-core/node_modules/source-map/package.json.944775175'
npm WARN rollback Rolling back adjust-sourcemap-loader@1.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/adjust-sourcemap-loader/node_modules/camelcase/package.json.3608494142'
npm ERR! path /home/vagrant/code/node_modules/abbrev/package.json.131979142
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename
npm ERR! ETXTBSY: text file is busy, rename '/home/vagrant/code/node_modules/abbrev/package.json.131979142' -> '/home/vagrant/code/node_modules/abbrev/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-08-10T13_37_30_357Z-debug.log

```

´´´shell

> npm run production

npm WARN npm npm does not support Node.js v10.8.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> @ production /home/vagrant/code
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:236:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-08-10T13_55_31_942Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-08-10T13_55_31_960Z-debug.log

´´´

## Steps to reproduce
1. Install Windows 10
* Install Virtualbox
* Install Vagrant
* Clone Homestead
* Init and configure Homestead
* Clone Laravel
* Run npm install

## References

** [Github-NPM-20950](https://github.com/npm/npm/issues/20950)
* [exceptionshub](https://exceptionshub.com/error-etxtbsy-text-file-is-busy-on-npm-install.html)
* [Github-NPM-9979](https://github.com/npm/npm/issues/9979) 
* [Github-Npm-20605](https://github.com/npm/npm/issues/20605)
* [Homestead-866](https://github.com/laravel/homestead/issues/866)
* .... and so on

**Comment by Eskaaa** [comment]
Hello, thank you very much for spending time on this issue.

```shell
vagrant@dev-local:~/code$ npm install
npm WARN rollback Rolling back abbrev@1.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/abbrev/package.json.3533218038'
npm WARN rollback Rolling back acorn-dynamic-import@2.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/acorn-dynamic-import/package.json.1733404457'
npm WARN rollback Rolling back acorn@4.0.13 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/acorn-dynamic-import/node_modules/acorn/package.json.3534752001'
npm WARN rollback Rolling back ajv-keywords@3.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ajv-keywords/package.json.4048504180'
npm WARN rollback Rolling back camelcase@1.2.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/adjust-sourcemap-loader/node_modules/camelcase/package.json.4125958182'
npm WARN rollback Rolling back amdefine@1.0.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/amdefine/package.json.3495638571'
npm WARN rollback Rolling back ansi-regex@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-regex/package.json.4286723812'
npm WARN rollback Rolling back ansi-html@0.0.7 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-html/package.json.1606666357'
npm WARN rollback Rolling back alphanum-sort@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/alphanum-sort/package.json.2478757196'
npm WARN rollback Rolling back ansi-wrap@0.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-wrap/package.json.2595492549'
npm WARN rollback Rolling back aproba@1.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aproba/package.json.4170576557'
npm WARN rollback Rolling back ansi-gray@0.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ansi-gray/package.json.3423865556'
npm WARN rollback Rolling back archive-type@3.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/archive-type/package.json.2243657005'
npm WARN rollback Rolling back file-type@3.9.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/archive-type/node_modules/file-type/package.json.3641111460'
npm WARN rollback Rolling back arr-flatten@1.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-flatten/package.json.3458930831'
npm WARN rollback Rolling back arr-diff@4.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-diff/package.json.2536690881'
npm WARN rollback Rolling back arr-union@3.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/arr-union/package.json.2980387820'
npm WARN rollback Rolling back array-differ@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-differ/package.json.3923987795'
npm WARN rollback Rolling back array-find-index@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-find-index/package.json.2653698088'
npm WARN rollback Rolling back array-flatten@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-flatten/package.json.225453374'
npm WARN rollback Rolling back array-uniq@1.0.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-uniq/package.json.1358823576'
npm WARN rollback Rolling back array-union@1.0.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-union/package.json.3110248508'
npm WARN rollback Rolling back array-unique@0.3.2 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/array-unique/package.json.857394355'
npm WARN rollback Rolling back asap@2.0.6 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/asap/package.json.1844131700'
npm WARN rollback Rolling back assign-symbols@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/assign-symbols/package.json.320233826'
npm WARN rollback Rolling back ast-types@0.9.6 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/ast-types/package.json.2563780366'
npm WARN rollback Rolling back assert-plus@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/assert-plus/package.json.1547195921'
npm WARN rollback Rolling back async-each@1.0.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-each/package.json.353144535'
npm WARN rollback Rolling back async-each-series@1.1.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-each-series/package.json.288915879'
npm WARN rollback Rolling back asynckit@0.4.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/asynckit/package.json.213461718'
npm WARN rollback Rolling back async-foreach@0.1.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/async-foreach/package.json.1555186804'
npm WARN rollback Rolling back aws-sign2@0.7.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aws-sign2/package.json.621248267'
npm WARN rollback Rolling back babel-plugin-syntax-async-functions@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-async-functions/package.json.3781083655'
npm WARN rollback Rolling back ansi-styles@2.2.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-code-frame/node_modules/ansi-styles/package.json.3101013630'
npm WARN rollback Rolling back atob@2.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/atob/package.json.2630077391'
npm WARN rollback Rolling back supports-color@2.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-code-frame/node_modules/supports-color/package.json.1297393194'
npm WARN rollback Rolling back babel-plugin-syntax-exponentiation-operator@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-exponentiation-operator/package.json.2001068536'
npm WARN rollback Rolling back aws4@1.8.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/aws4/package.json.1683651057'
npm WARN rollback Rolling back babel-plugin-syntax-flow@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-flow/package.json.4286610413'
npm WARN rollback Rolling back babel-plugin-syntax-object-rest-spread@6.13.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-object-rest-spread/package.json.3269638813'
npm WARN rollback Rolling back babel-plugin-syntax-jsx@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-jsx/package.json.1915752970'
npm WARN rollback Rolling back babel-plugin-syntax-trailing-function-commas@6.22.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-plugin-syntax-trailing-function-commas/package.json.3589691704'
npm WARN rollback Rolling back babylon@6.18.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babylon/package.json.615632171'
npm WARN rollback Rolling back balanced-match@1.0.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/balanced-match/package.json.3838495647'
npm WARN rollback Rolling back batch@0.6.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/batch/package.json.3571334323'
npm WARN rollback Rolling back base64-js@0.0.8 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/base64-js/package.json.1460887819'
npm WARN rollback Rolling back beeper@1.1.1 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/beeper/package.json.3883539289'
npm WARN rollback Rolling back babel-code-frame@6.26.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-code-frame/node_modules/supports-color/package.json.1297393194'
npm WARN rollback Rolling back babel-core@6.26.3 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/babel-core/node_modules/source-map/package.json.2284816037'
npm WARN rollback Rolling back adjust-sourcemap-loader@1.2.0 failed (this is probably harmless): ETXTBSY: text file is busy, unlink '/home/vagrant/code/node_modules/adjust-sourcemap-loader/node_modules/camelcase/package.json.4125958182'
npm ERR! path /home/vagrant/code/node_modules/ansi-gray/package.json.3423865556
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename
npm ERR! ETXTBSY: text file is busy, rename '/home/vagrant/code/node_modules/ansi-gray/package.json.3423865556' -> '/home/vagrant/code/node_modules/ansi-gray/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-08-11T13_23_26_420Z-debug.log

```

**Comment by Eskaaa** [comment]
Yes I did. several times. I tried to install with --save flag, without binary links. I run the install comand with sudo. Reinstalled everything.

**Comment by Eskaaa** [comment]
Here is my Vagrantfile.
I connect to ssh via putty. Run as local admin, or via powershell, as local admin, too.
yarn works fine. it is only npm what cause this errors.

```php
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadYamlPath = File.expand_path("Homestead.yaml", File.dirname(__FILE__))
homesteadJsonPath = File.expand_path("Homestead.json", File.dirname(__FILE__))
afterScriptPath = "after.sh"
aliasesPath = "aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end

    config.vm.provider "virtualbox" do |v|
        v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end
end


```

**Comment by jozeflambrecht** [comment]
@Eskaaa Same problem. Had to reinstall Windows 10 as well. Do you have a solution in the meantime (other than the workaround posted above)?

**Comment by Eskaaa** [comment]
Hello. No, I did not found a better solution, than installing Node on the host machine. Hope the problem can be fixed in the future.

**Comment by dylanbr** [comment]
The underlying problem is related to how Windows file locking is handled by Virtualbox sharing. It happens whether using standard shared folders (vboxsf) or nfs. If a file is opened or read (locked) by another process while ```npm``` is trying to change it the whole install process fails.

How to fix:

1. Run ```vagrant up``` (and other commands) from an administrator terminal. This ensures symlinks work correctly. There are other ways to enable symlinks - if you use one of them be sure to test them out using ```ln -s a b``` within the shared folder.
2. Ensure that no other process opens any of the files in the shared folder by either disabling the process or excluding the vagrant folder. This includes, but is not limited to:
    1. Windows Defender or other anti virus software
    2. Windows search index or other indexing software
    3. Dropbox or other file synchronisation software.

If you are still having issues with point 2 above, you can use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), filtered to your vagrant directory, to detect access by any process other than Virtualbox (VBoxHeadless.exe).

With the above in place I am able to successfully run ```npm install``` without issue.
